name: publish site
on: [push]
jobs:
    prepare:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: step
          run: ls
    build-site:
      runs-on: ubuntu-latest
      container: clojure:lein
      steps:
        - run: ls