name: publish site
on: [push]
jobs:
    prepare:
      runs-on: ubuntu-latest
      steps:
        - run: ls
    build-site:
      runs-on: ubuntu-latest
      container: clojure:lein
      steps:
        - run: ls