name: publish site
on:
  push:
    branches:
      - static-site
jobs:
    trigger-site-build:
      runs-on: ubuntu-latest
      env:
        PUBLISH_GITHUB_WEBSITE_TOKEN: ${{ secrets.PUBLISH_GITHUB_WEBSITE_TOKEN }}
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: trigger
          run: workflows/trigger-site-build.sh