name: publish site
on:
  push:
    branches:
      - static-site
jobs:
    #prepare:
    #  runs-on: ubuntu-latest
    #  steps:
    #    - name: checkout
    #      uses: actions/checkout@v4
    #    - name: test1
    #      run: ls
    #    - name: test2
    #      run: pwd
    build-site:
      runs-on: ubuntu-latest
      container: clojure:lein
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: build
          run: lein build-site
        - name: package
          run: tar -vczf github-pages -C target/site
        - name: check
          run: ls
        - name: upload
          uses: actions/upload-pages-artifact@v3
          with:
            path: "."